// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
    export interface UniwindConfig {
        themes: readonly ['light', 'dark', 'ocean-light', 'ocean-dark', 'forest-light', 'forest-dark', 'sunset-light', 'sunset-dark', 'lavender-light', 'lavender-dark']
    }
}

export {}
